#[shell]
# program               = "/usr/bin/zsh"
# args                  = [ "--login", ]

#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
TERM                  = "xterm-256color"

[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
padding               = { x = 6, y = 6 }
#dynamic_padding       = true
#decorations           = "None"
opacity               = 0.9
#blur                  = true
#startup_mode          = "Windowed"
title                 = "Alacritty"
dynamic_title         = true
class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"


[scrolling]
history               = 5000
#multiplier            = 3

[font]
normal                = { family = "Hack Nerd Font", style = "Regular" }
bold                  = { family = "Hack Nerd Font", style = "Bold" }
italic                = { family = "Hack Nerd Font", style = "Italic" }
bold_italic           = { family = "Hack Nerd Font", style = "Bold Italic" }
size                  = 13.25
offset                = { x = 0, y = 0 }
#glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[colors]
#transparent_background_colors = false
draw_bold_text_with_bright_colors = true

#[bell]
#animation             = "EaseOutExpo"
#duration              = 0
#color                 = "#C0C5CE"
#command               = { program = "notify-send", args = ["alacritty", "bell",] }

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Block"
blinking              = "Off"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 750
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[hints]
#alphabet              = "jfkdls;ahgurieowpq"

#[[hints.enabled]]
#command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
#hyperlinks            = true
#post_processing       = true
#persist               = false
#mouse.enabled         = true
#binding               = { key = "U", mods = "Control|Shift" }
#regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]

[debug]

[general]
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

import = [
  # uncomment the palette you want below:
  # "~/.config/alacritty/palettes/tokyonight-storm.toml"
  "~/.config/alacritty/palettes/tokyonight.toml"
  # "~/.config/alacritty/palettes/dracula.toml"
  # "~/.config/alacritty/palettes/gruvbox-dark.toml"
  # "~/.config/alacritty/palettes/gruvbox-material-medium-dark.toml"
  # "~/.config/alacritty/palettes/ayu-light.toml"
  # "~/.config/alacritty/palettes/ayu-mirage.toml"
  # "~/.config/alacritty/palettes/ayu-dark.toml"
  # "~/.config/alacritty/palettes/catppuccin-mocha.toml"
  # "~/.config/alacritty/palettes/catppuccin-macchiato.toml"
]
#render_timer          = false
#persistent_logging    = false
#log_level             = "Warn"
#renderer              = "None"
#print_events          = false
#highlight_damage      = false
#prefer_egl            = false
